language: node_js
rvm:
 - 6.1.x
 
sudo: required

services:
  - docker
 
before_install:
 - docker-compose build 

install:
- npm install
- npm -g install @angular/cli

bdfore_script:
 - ng test --single-run

script:
 - ng build
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
